resolver: ghc-8.0.1

packages:
- '.'

extra-deps:
  - bifunctors-5.3
  - http-conduit-2.1.10.1
  - mtl-2.2.1
  - network-2.6.2.1
  - regex-pcre-0.94.4
  - split-0.2.3.1
  - tagsoup-0.13.10
  - text-1.2.2.1
  - aeson-0.11.2.0
  - base-orphans-0.5.4
  - comonad-5
  - conduit-1.2.6.6
  - conduit-extra-1.1.13.1
  - data-default-class-0.1.0
  - exceptions-0.8.2.1
  - http-client-0.4.28
  - http-client-tls-0.2.4
  - http-types-0.9
  - lifted-base-0.2.3.6
  - monad-control-1.0.1.0
  - regex-base-0.93.2
  - resourcet-1.1.7.4
  - semigroups-0.18.1
  - tagged-0.8.4
  - transformers-compat-0.5.1.4
  - async-2.1.0
  - attoparsec-0.13.0.2
  - base64-bytestring-1.0.0.1
  - blaze-builder-0.4.0.2
  - case-insensitive-1.2.0.6
  - connection-0.2.5
  - contravariant-1.4
  - cookie-0.4.2
  - distributive-0.5.0.2
  - dlist-0.7.1.2
  - fail-4.9.0.0
  - hashable-1.2.4.0
  - mime-types-0.1.0.7
  - mmorph-1.0.6
  - network-uri-2.6.1.0
  - primitive-0.6.1.0
  - random-1.1
  - scientific-0.3.4.6
  - stm-2.4.4.1
  - streaming-commons-0.1.15.5
  - syb-0.6
  - tls-1.3.8
  - transformers-base-0.4.4
  - unordered-containers-0.2.7.0
  - vector-0.11.0.0
  - StateVar-1.1.0.4
  - asn1-encoding-0.9.3
  - asn1-types-0.3.2
  - byteable-0.1.1
  - cereal-0.5.1.0
  - cryptonite-0.15
  - memory-0.13
  - old-locale-1.0.0.7
  - parsec-3.1.11
  - socks-0.5.5
  - void-0.7.1
  - x509-1.6.3
  - x509-store-1.6.1
  - x509-system-1.6.3
  - x509-validation-1.6.3
  - zlib-0.6.1.1
  - asn1-parse-0.9.4
  - hourglass-0.2.10
  - pem-0.2.2



flags: {}

extra-package-dbs: []
